name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # or your preferred version

    - name: Install dependencies
      run: npm install # Adjust this if needed

    - name: Set the API key environment variable
      run: echo "Nasa_API_KEY=${{ secrets.NASA_API_KEY }}" >> $GITHUB_ENV

    - name: Replace API key using Node.js script
      run: node .github/workflows/replace.js  # Use the correct path

    - name: Build project
      run: npm run build # Adjust this if you have a build command

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public # Adjust this to your output directory
